before_script:
    - export http_proxy=http://proxy.swmed.edu:3128
    - export https_proxy=http://proxy.swmed.edu:3128
    - export ftp_proxy=http://proxy.swmed.edu:3128
    - export no_proxy="127.0.0.1,localhost"
    - uname -a
    - free -m
    - df -h
    - ulimit -a
stages:
    - build
    - test
    - buildExtra
jobBuildRelease:
    image: zhanxw/rvtests-docker:latest
    stage: build
    script:
        - make
        - FN=/dist/rvtests-`date +"%Y%m%d"`-`git rev-parse HEAD|cut -c 1-6`-linux64-static.tar.gz; cd .. && tar zvcf ${FN} rvtests/executable/rvtest rvtests/executable/vcf2kinship rvtests/example rvtests/README.md && echo "Output file name is ${FN}"
jobTest:
    image: zhanxw/rvtests-docker:dev
    stage: test
    script:
        - make debug
        - (for i in base libVcf regression libBgen; do echo "Task = ${i}"; make -C ${i}/test; done)
        - (for i in base libVcf regression libBgen; do echo "Task = ${i}"; make check -C ${i}/test; done)
jobBuildDebug:
    image: zhanxw/rvtests-docker:dev-ubuntu
    stage: buildExtra
    script:
        - make debug
        - FN=/dist/rvtests-debug-`date +"%Y%m%d"`-`git rev-parse HEAD|cut -c 1-6`-linux64-static.tar.gz; cd .. && tar zvcf ${FN} rvtests/executable/dbg/rvtest rvtests/executable/dbg/vcf2kinship rvtests/example rvtests/README.md && echo "Output file name is ${FN}"
jobBuildProfile:
    image: zhanxw/rvtests-docker:dev-ubuntu
    stage: buildExtra
    script:
        - make profile
        - FN=/dist/rvtests-profile-`date +"%Y%m%d"`-`git rev-parse HEAD|cut -c 1-6`-linux64-static.tar.gz; cd .. && tar zvcf ${FN} rvtests/executable/dbg/rvtest rvtests/executable/dbg/vcf2kinship rvtests/example rvtests/README.md && echo "Output file name is ${FN}"
    allow_failure: true

#jobDeploy:
#    stage: deploy
#    script:
#        - echo "Packing RVTESTS"
#        - make
#    environment:
#        name: staging
#        url: http:staging-rvtests.bunny.swmed.edu
#    when: "manual"
